repos:
  - repo: https://github.com/tomcatling/black-nb
    rev: "0.6"
    hooks:
      - id: black-nb
        args: [--verbose, --clear-output]
  - repo: https://github.com/psf/black
    rev: "22.1.0"
    hooks:
      - id: black
